ecmaFeatures:
  jsx: true
env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
globals:
  $: false
  jQuery: false
  require: false
  Waypoint: false
rules:
  indent:
    - 1
    - tab
  linebreak-style:
    - 1
    - windows
  quotes: ["error", "double", {avoidEscape: true}]
  semi:
    - 2
    - always
